### ISSUE TITLE
FABRIC 1.20.1 - Kicked for placing insulated wire

### ISSUE THREAD

**Issue by vitecekuwu** [Kneelawk/WiredRedstone#46]
Honestly, no idea what is happening in here. The log is with the debug thingy enabled in config. When i place the insulated wire, it kicks me but still places it.

```
[09:03:23] [Render thread/INFO]: [STDOUT]: TagKey[minecraft:item / wiredredstone:insulated_wires]
[09:03:23] [Server thread/INFO]: [STDOUT]: TagKey[minecraft:item / wiredredstone:insulated_wires]
[09:03:23] [Render thread/INFO]: [STDERR]: alexiil.mc.lib.net.InvalidInputDataException: Packet failed to read correctly!

Packet: NetIdDataK <PartContainer> '.block_entity.libmultipart:container.container.add_part'
Payload Length: 43
Reader Index: 43. (Marked by '#')
Error: Already contained a part with the uniqueId 1
[{PartHolder uid = 38414906048, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@1e6efead}, {PartHolder uid = 38414906049, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@38cd91a4}, {PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@7097ea5f}, {PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@323ca18e}]
{38414906049=>{PartHolder uid = 38414906049, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@38cd91a4}, 1=>{PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@323ca18e}, 38414906048=>{PartHolder uid = 38414906048, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@1e6efead}}
Raw Bytes:
+---------
| 44 7b 42 00 00 00 00 00 00 00 01 1c 77 69 72 65 64 72 65 64 | D{B         wiredred
| 73 74 6f 6e 65 3a 69 6e 73 75 6c 61 74 65 64 5f 77 69 72 65 | stone:insulated_wire
| 00 00 00#                                                   |    
+---------
Payload Types: 11
Payload Data:
+---------
|ParentNetIdSingle<class_2586> '.block_entity'
| BlockPos: [ -5, -60, -3 ]
+---------
|ParentNetIdCast<class_2586, MultipartBlockEntity> '.block_entity.libmultipart:container'
+---------
|ParentNetIdExtractor<MultipartBlockEntity, PartContainer> '.block_entity.libmultipart:container.container'
+---------
|NetIdDataK <PartContainer> '.block_entity.libmultipart:container.container.add_part'
| long: 1
| string: "wiredredstone:insulated_wire"
| fixed_int (3): 0
| byte: 0
| fixed_int (4): 0
| byte: 0
+---------


[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.InternalMsgUtil.onReceive(InternalMsgUtil.java:470)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.BufferedConnection.onReceiveRawData(BufferedConnection.java:135)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.lambda$onClientReceivePacket$3(CoreMinecraftNetUtil.java:205)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:115)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1175)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[09:03:23] [Render thread/INFO]: [STDERR]: Caused by: alexiil.mc.lib.net.InvalidInputDataException: Already contained a part with the uniqueId 1
[{PartHolder uid = 38414906048, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@1e6efead}, {PartHolder uid = 38414906049, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@38cd91a4}, {PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@7097ea5f}, {PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@323ca18e}]
{38414906049=>{PartHolder uid = 38414906049, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@38cd91a4}, 1=>{PartHolder uid = 1, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@323ca18e}, 38414906048=>{PartHolder uid = 38414906048, part = com.kneelawk.wiredredstone.part.InsulatedWirePart@1e6efead}}
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.multipart.impl.PartContainer.readAddPart(PartContainer.java:458)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.NetIdDataK.receive(NetIdDataK.java:47)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.NetIdTyped.receive(NetIdTyped.java:34)
[09:03:23] [Render thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.InternalMsgUtil.onReceive(InternalMsgUtil.java:331)
[09:03:23] [Render thread/INFO]: [STDERR]: 	... 15 more
[09:03:23] [Server thread/INFO]: VoidMage lost connection: Disconnected
```

![image](https://github.com/Kneelawk/WiredRedstone/assets/144355142/7b3008af-5b16-4ad6-8940-a3285af0bac2)

[latest.log](https://github.com/Kneelawk/WiredRedstone/files/14896076/latest.log) (whole log, if needed)

**Comment by Kneelawk** [comment]
This is likely a mod conflict, though I have no idea with what mod. Do you think you could send me the modpack so I can bisect it?

**Comment by vitecekuwu** [comment]
[Fabric_Origins_Dev_Pipered_1.1.2.mrpack.zip](https://github.com/Kneelawk/WiredRedstone/files/14896127/Fabric_Origins_Dev_Pipered_1.1.2.mrpack.zip) here's the whole modpack (its .mrpack inside a .zip, since github doesn't support attaching .mrpack)

**Comment by Kneelawk** [comment]
The automated bisect failed. I'm going to have to manually bisect this when I have a bit more time.

**Comment by xLuna97** [comment]
Heya, so i found out what the problem in my Modpack is, its the mod "Labeling Containers" https://www.curseforge.com/minecraft/mc-mods/labelling-containers 
Hope it helps a bit :)
